linter:
  rules:
    # ====================
    # Error Rules
    # ====================

    always_use_package_imports: true
    avoid_empty_else: true
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    #    avoid_web_libraries_in_flutter (experimental): true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    control_flow_in_finally: true

    #changed
    diagnostic_describe_all_properties: false

    unsafe_html: false
    undefined_prefixed_name: false

    empty_statements: true
    hash_and_equals: true
    #    invariant_booleans (experimental): true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_relative_imports: false
    prefer_void_to_null: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: tru
    valid_regexps: true

    # ====================
    # Style
    # ====================

    # Maybe false
    always_declare_return_types: true

    always_put_required_named_parameters_first: true
    always_require_non_null_named_parameters: false
    always_specify_types: false
    annotate_overrides: true
    avoid_annotating_with_dynamic: false
    avoid_as: false
    avoid_bool_literals_in_conditional_expressions: true

    # Should be true in the future but for now it's ok
    avoid_catches_without_on_clauses: false
    avoid_catching_errors: false

    # Maybe we need this at string files
    avoid_classes_with_only_static_members: false

    avoid_double_and_int_checks: true

    # Interesting: https://dart-lang.github.io/linter/lints/avoid_equals_and_hash_code_on_mutable_classes.html
    avoid_equals_and_hash_code_on_mutable_classes: true

    avoid_escaping_inner_quotes: false
    avoid_field_initializers_in_const_classes: true
    avoid_function_literals_in_foreach_calls: true

    # Interesting: https://dart-lang.github.io/linter/lints/avoid_implementing_value_types.html
    avoid_implementing_value_types: true

    avoid_init_to_null: true
    avoid_js_rounded_ints: true
    avoid_null_checks_in_equality_operators: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_shadowing_type_parameters: false
    avoid_single_cascade_in_expression_statements: true
    avoid_types_on_closure_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true
    avoid_void_async: true
    camel_case_extensions: true
    camel_case_types: true
    cascade_invocations: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    do_not_use_environment: true
    empty_catches: true
    empty_constructor_bodies: true
    exhaustive_cases: true
    file_names: true
    flutter_style_todos: false
    implementation_imports: true
    #    invariant_booleans (experimental): true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    library_names: true
    library_prefixes: true
    lines_longer_than_80_chars: false
    missing_whitespace_between_adjacent_strings: true
    #    no_default_cases (experimental): true
    no_runtimeType_toString: true
    non_constant_identifier_names: true
    null_closures: true
    omit_local_variable_types: true
    one_member_abstracts: true
    only_throw_errors: false
    overridden_fields: false

    # maybe true in the future
    package_api_docs: false

    package_prefixed_library_names: true
    parameter_assignments: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: false
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_contains: true
    prefer_double_quotes: false
    prefer_equal_for_default_values: true
    prefer_expression_function_bodies: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_foreach: false
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_int_literals: false
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_mixin: true
    prefer_null_aware_operators: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    public_member_api_docs: false
    recursive_getters: true
    sized_box_for_whitespace: true
    slash_for_doc_comments: true
    sort_child_properties_last: true
    sort_constructors_first: false
    sort_pub_dependencies: false
    sort_unnamed_constructors_first: false
    type_annotate_public_apis: true
    type_init_formals: true
    unawaited_futures: false
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_final: false
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_is_even_rather_than_modulo: true
    use_raw_strings: false
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
    void_checks: true

    # ====================
    # Pub Rules
    # ====================

    package_names: true

analyzer:
  exclude:
    - lib/injection.dart
    - lib/injection.config.dart
    - lib/generated_plugin_registrant.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.gr.dart
    - lib/generated/**
    - test/_data/**
  errors:
    always_use_package_imports: error
    avoid_empty_else: warning
    avoid_print: info
    avoid_relative_lib_imports: error
    avoid_returning_null_for_future: warning
    avoid_slow_async_io: warning
    avoid_types_as_parameter_names: error
    cancel_subscriptions: info
    close_sinks: info
    comment_references: info
    control_flow_in_finally: warning
    empty_statements: warning
    hash_and_equals: warning
    iterable_contains_unrelated_type: error
    list_remove_unrelated_type: error
    literal_only_boolean_expressions: warning
    no_adjacent_strings_in_list: warning
    no_duplicate_case_values: warning
    no_logic_in_create_state: error
    prefer_void_to_null: warning
    test_types_in_equals: warning
    throw_in_finally: error
    unnecessary_statements: warning
    unrelated_type_equality_checks: error
    unsafe_html: error
    use_key_in_widget_constructors: warning
    valid_regexps: error
    always_declare_return_types: error
    always_put_required_named_parameters_first: warning
    annotate_overrides: warning
    avoid_bool_literals_in_conditional_expressions: warning
    avoid_double_and_int_checks: warning
    avoid_equals_and_hash_code_on_mutable_classes: warning
    avoid_field_initializers_in_const_classes: warning
    avoid_function_literals_in_foreach_calls: warning
    avoid_implementing_value_types: warning
    avoid_init_to_null: warning
    avoid_js_rounded_ints: error
    avoid_null_checks_in_equality_operators: warning
    avoid_positional_boolean_parameters: warning
    avoid_private_typedef_functions: error
    avoid_redundant_argument_values: warning
    avoid_renaming_method_parameters: error
    avoid_return_types_on_setters: warning
    avoid_returning_null: warning
    avoid_returning_null_for_void: error
    avoid_returning_this: error
    avoid_setters_without_getters: warning
    avoid_single_cascade_in_expression_statements: warning
    avoid_types_on_closure_parameters: warning
    avoid_unnecessary_containers: warning
    avoid_unused_constructor_parameters: warning
    await_only_futures: warning
    avoid_void_async: error
    camel_case_extensions: warning
    camel_case_types: warning
    cascade_invocations: warning
    constant_identifier_names: warning
    curly_braces_in_flow_control_structures: warning
    directives_ordering: warning
    do_not_use_environment: warning
    empty_catches: warning
    empty_constructor_bodies: warning
    exhaustive_cases: error
    file_names: warning
    implementation_imports: warning
    join_return_with_assignment: warning
    leading_newlines_in_multiline_strings: warning
    library_names: warning
    library_prefixes: warning
    missing_whitespace_between_adjacent_strings: warning
    no_runtimeType_toString: warning
    non_constant_identifier_names: warning
    null_closures: warning
    omit_local_variable_types: warning
    one_member_abstracts: info
    package_prefixed_library_names: warning
    parameter_assignments: error
    prefer_adjacent_string_concatenation: warning
    prefer_asserts_in_initializer_lists: warning
    prefer_collection_literals: error
    prefer_conditional_assignment: warning
    prefer_const_constructors: warning
    prefer_const_constructors_in_immutables: warning
    prefer_const_declarations: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_constructors_over_static_methods: warning
    prefer_contains: warning
    prefer_equal_for_default_values: warning
    prefer_expression_function_bodies: warning
    prefer_final_fields: warning
    prefer_final_in_for_each: warning
    prefer_final_locals: warning
    prefer_for_elements_to_map_fromIterable: warning
    prefer_function_declarations_over_variables: warning
    prefer_generic_function_type_aliases: warning
    prefer_if_elements_to_conditional_expressions: warning
    prefer_if_null_operators: warning
    prefer_initializing_formals: warning
    prefer_inlined_adds: warning
    prefer_interpolation_to_compose_strings: warning
    prefer_is_empty: warning
    prefer_is_not_empty: warning
    prefer_is_not_operator: warning
    prefer_iterable_whereType: warning
    prefer_mixin: warning
    prefer_null_aware_operators: warning
    prefer_single_quotes: warning
    prefer_spread_collections: warning
    prefer_typing_uninitialized_variables: error
    provide_deprecation_message: warning
    recursive_getters: warning
    sized_box_for_whitespace: warning
    slash_for_doc_comments: warning
    sort_child_properties_last: warning
    type_annotate_public_apis: error
    type_init_formals: error
    unnecessary_await_in_return: warning
    unnecessary_brace_in_string_interps: warning
    unnecessary_const: warning
    unnecessary_getters_setters: warning
    unnecessary_lambdas: warning
    unnecessary_new: error
    unnecessary_null_aware_assignments: warning
    unnecessary_null_in_if_null_operators: warning
    unnecessary_overrides: warning
    unnecessary_parenthesis: warning
    unnecessary_raw_strings: warning
    unnecessary_string_escapes: warning
    unnecessary_string_interpolations: warning
    unnecessary_this: warning
    use_full_hex_values_for_flutter_colors: warning
    use_function_type_syntax_for_parameters: warning
    use_is_even_rather_than_modulo: warning
    use_rethrow_when_possible: warning
    use_setters_to_change_properties: warning
    use_string_buffers: warning
    use_to_and_as_if_applicable: warning
    void_checks: error
    package_names: warning
  # strong-mode:
  #   implicit-casts: false
  #   implicit-dynamic: false
