name: byte_adventures
description: This is the project for the B8+ conference website

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_strategy: ^0.2.0-nullsafety.0
  url_launcher: ^6.0.3
  firebase_core: ^1.0.3
  firebase_analytics: ^8.0.0
  google_fonts: ^2.0.0
  rive: ^0.7.1
  font_awesome_flutter: ^9.0.0
  intl: ^0.17.0-nullsafety.2
  universal_ui: ^0.0.8
  carousel_slider: ^4.0.0-nullsafety.0
  auto_size_text: ^2.1.0

dev_dependencies:
  build_runner: ^1.10.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/animations/mascot.riv
    - google_fonts/
flutter_intl:
  enabled: true
