name: Deploy gather redirect
on:
  push:
    branches:
      - master
    paths:
      - "gather_redirect/**"
jobs:
  build_web:
    name: deploy redirect folder
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v1
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: firebase deploy hosting --public gather_redirect
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: b8adventures
