name: Deploy Website
on:
  push:
    branches:
      - master
    paths-ignore:
      - "gather_redirect/**"
jobs:
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: flutter build web --no-sound-null-safety --release
      - name: Deploy 
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_TOKEN }}
          projectId: b8adventures
          target: b8adventures
